import axiosInstance from '../api/axiosInstance';
import type { ChatMessage } from '../types';

type AiChatResponse = {
  answer?: string;
  content?: string;
  error?: string;
};

function extractAssistantText(payload: AiChatResponse): string {
  const value = payload.answer ?? payload.content;
  return typeof value === 'string' && value.trim().length > 0
    ? value
    : 'No response generated by AI service.';
}

export async function sendChatMessage(messages: ChatMessage[]): Promise<string> {
  const response = await axiosInstance.post<AiChatResponse>('/ai/chat', { messages });
  return extractAssistantText(response.data);
}

const API_BASE_URL = (import.meta.env.VITE_API_URL || '/api/v1').replace(/\/$/, '');

// The Vite dev proxy (server.proxy in vite.config.ts) buffers chunked/SSE
// responses instead of forwarding bytes as they arrive — measured ~3-4s added
// to first-byte latency vs hitting the backend directly. CORS already allows
// this origin (see ALLOWED_ORIGINS in backend/.env), so for the one endpoint
// where streaming is the whole point, skip the proxy and call the backend
// origin straight. Falls back to the (proxied) relative API base when no
// backend origin is configured, e.g. in production.
const BACKEND_ORIGIN = (import.meta.env.VITE_BACKEND_URL || '').replace(/\/$/, '');
const STREAM_URL = BACKEND_ORIGIN
  ? `${BACKEND_ORIGIN}/api/v1/ai/chat/stream`
  : `${API_BASE_URL}/ai/chat/stream`;

/**
 * Streams /ai/chat/stream (SSE) so the UI can render text as it's generated —
 * first words land in well under 1s instead of waiting for the full reply.
 * Falls back to the plain /ai/chat endpoint if streaming itself fails to connect.
 */
export async function chatWithAIAgent(
  userMessage: string,
  conversationHistory: ChatMessage[] = [],
  onDelta?: (chunkText: string, fullTextSoFar: string) => void,
): Promise<string> {
  const messages: ChatMessage[] = [
    ...conversationHistory,
    { role: 'user', content: userMessage },
  ];

  const token = localStorage.getItem('hse_jwt_token');
  let response: Response;
  try {
    response = await fetch(STREAM_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({ messages }),
    });
  } catch {
    // Network-level failure to even open the stream (e.g. proxy strips SSE) —
    // fall back to the non-streaming endpoint rather than fail outright.
    return sendChatMessage(messages);
  }

  if (!response.ok || !response.body) {
    return sendChatMessage(messages);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let full = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    const events = buffer.split('\n\n');
    buffer = events.pop() ?? '';
    for (const rawEvent of events) {
      const line = rawEvent.split('\n').find((l) => l.startsWith('data:'));
      if (!line) continue;
      try {
        const data = JSON.parse(line.slice('data:'.length).trim());
        if (typeof data.delta === 'string') {
          full += data.delta;
          onDelta?.(data.delta, full);
        }
      } catch {
        // ignore malformed/partial event
      }
    }
  }

  return full.trim().length > 0 ? full : 'No response generated by AI service.';
}

export async function analyzeViolations(violationData: unknown): Promise<string> {
  const prompt = `Analyze the following violation dataset and return: key trends, high-risk areas, and top recommendations.\n\nData:\n${JSON.stringify(violationData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export async function getPredictedRisks(historicalData: unknown): Promise<string> {
  const prompt = `Based on this historical data, provide a risk forecast with probability and preventive actions.\n\nData:\n${JSON.stringify(historicalData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export async function generateRecommendations(context: string): Promise<string> {
  return chatWithAIAgent(`Generate prioritized HSE recommendations from this context:\n\n${context}`);
}

export async function analyzeZoneRisks(zoneData: unknown): Promise<string> {
  const prompt = `Assess zone-level risk from the dataset and recommend controls by priority.\n\nData:\n${JSON.stringify(zoneData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export type AskDataReply = {
  answer: string;
  /** The SELECT(s) Claude actually ran — safe to show; they are read-only and org-scoped. */
  sql: string[];
  model?: string;
};

/**
 * Ask a question that has to be answered from the database rather than from the
 * precomputed briefing — "how many incidents last month", "which site has the
 * most overdue CAPAs". Claude writes a SELECT, the backend validates and runs it
 * (read-only, org-scoped by the JWT), then phrases the result.
 *
 * Not streamed: the reply only exists after the query round-trip, so there is
 * nothing to stream until the very end.
 */
export async function askData(question: string): Promise<AskDataReply> {
  const response = await axiosInstance.post<AskDataReply>('/ai/ask-data', { question });
  const body = response.data ?? ({} as AskDataReply);
  return {
    answer:
      typeof body.answer === 'string' && body.answer.trim().length > 0
        ? body.answer
        : 'No answer generated for that question.',
    sql: Array.isArray(body.sql) ? body.sql : [],
    model: body.model,
  };
}

export type { ChatMessage };

export default {
  sendChatMessage,
  chatWithAIAgent,
  askData,
  analyzeViolations,
  getPredictedRisks,
  generateRecommendations,
  analyzeZoneRisks,
};
